version: "3.8"

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:6.4-php8.2-apache
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    volumes:
      # WP本体（wp-config.php など）を永続化
      - wp_html:/var/www/html

      # 開発するwp-content
      - ./wp-content:/var/www/html/wp-content

      # 生成された静的HTML（ブラウザで /static/... で見える）
      - ./static:/var/www/html/static

      # ★静的テンプレ（list.html/detail.html）←これが今回のポイント
      - ./static-src:/var/www/html/static-src

  wpcli:
    image: wordpress:cli-php8.2
    depends_on:
      - db
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
    volumes:
      - wp_html:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./static:/var/www/html/static
      - ./static-src:/var/www/html/static-src
    working_dir: /var/www/html
    # さっきの Permission 対策（wp-config を作れた設定を常時適用）
    user: "33:33"

volumes:
  db_data:
  wp_html:
